server:
  port: 8080
  servlet:
    context-path: /job-portal

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/job_portal"
    username: root
    password: quochuy2k2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
